name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  rust-checks:
    uses: PurpleBooth/common-pipelines/.github/workflows/rust-check.yml@main
  release:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    needs:
      - rust-checks
    outputs:
      version_bump: ${{ steps.current_version.outputs.current_version != steps.previous_version.outputs.previous_version }}
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Get tags
        run: git fetch --tags origin
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.4.4
      - shell: bash
        run: cargo binstall --no-confirm cargo-edit
      - shell: bash
        run: cargo binstall --no-confirm cocogitto
      - id: previous_version
        run: |
          cog get-version | tee .version
          echo "previous_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash
      - name: Semver release
        id: release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          git config --global user.name "cog-bot"
          git config --global user.email "cog@example.com"
          cog bump --auto
      - id: current_version
        run: |
          cog get-version | tee .version
          echo "current_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash
